model:
  target: solarchip.SolarCHIP.solarchip_base
  params:
    # modal_list: ['hmi', '0094', '0131', '0171', '0193', '0211', '0304', '0335', '1600', '1700', '4500']
    save_memory: True
    ckpt_path: null
    base_model:
      target: solarchip.modules.CNN.AE_CNN
      params:
        contrastive_dim: 32
        ckpt_path: null

        ddconfig:
          double_z: False
          z_channels: 128
          resolution: 1024
          in_channels: 1
          out_ch: 1
          ch: 64 # initial channel number, will be multiplied by ch_mult at each downsample
          ch_mult: [1,1,1,1,2,2,2] # spatial downsample 64, channel upsample 4(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          use_linear_attn: False
          dropout: 0.0 

    loss_config:
      epochs: 50
      lr: 1e-3
      optimizer: "AdamW"
      scheduler: "CosineAnnealingLR"
      rec_loss_type: l2
      kl_weight: 0.0
      perceptual_weight: 0.0 # better not use perceptual loss for solar images, as it may cause color distortion
      cls_contrastive_weight: 0.0
      pat_contrastive_weight: 0.0
      int_contrastive_weight: 0.0

data:
  target: data.build.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    wrap: False
    train:
      target: data.dataset.SolarDataset.multimodal_dataset
      params:
        # modal_list: ['hmi', '0094', '0131', '0171', '0193', '0211', '0304', '0335', '1600', '1700', '4500']
        log1p_scale: 1
        load_imgs: False
        enhance_list:
          - 1024
          - 0.5
          - 360
        time_interval: 
          - 0
          - 5000
        time_step: 10
    validation:
      target: data.dataset.SolarDataset.multimodal_dataset
      params:
        # modal_list: ['hmi', '0094', '0131', '0171', '0193', '0211', '0304', '0335', '1600', '1700', '4500']
        log1p_scale: 1
        load_imgs: False
        enhance_list:
          - 1024
          - 0.5
          - 360
        time_interval: 
          - 5000
          - 5400
        time_step: 10


lightning:
  callbacks:
    image_logger:
      target: solarchip.utils.callback.SolarImageLogger
      params:
        batch_frequency: 19
        max_images: 2
        
    early_stop:
      target: pytorch_lightning.callbacks.EarlyStopping
      params:
            monitor: val_loss
            patience: 10

  modelcheckpoint:
    params:
      monitor: val_loss
      save_last: True
      save_top_k: 3
      every_n_epochs: 1
      save_weights_only: True

  trainer:
    max_epochs: 50
    precision: bf16
    # log_every_n_steps: 1
    # devices: [0,1]