model:
  target: solarchip.SolarCHIP
  params:
    modal_list: ['hmi', '0094', '0131', '0171', '0193', '0211', '0304', '0335', '1600', '1700', '4500']
    ckpt_path: null
    save_memory: False
    base_model:
      target: models.reconmodels.autoencoder.models.vae.CNN_VAE_v2.CNN_VAE_two
      params:
        ckpt_path: null
        vae_modal: 'aia0094_image'
        kl_weight: 0.1
        loss_type: 'MSE'

        dd_config:
          double_z: True
          z_channels: 8
          resolution: 1024
          in_channels: 1
          out_ch: 1
          ch: 16
          ch_mult: [1,2,2,2] # num_down = len(ch_mult)-1
          num_res_blocks: 4
          attn_resolutions: []
          dropout: 0.0

    loss_config:
      epochs: 100
      lr: 1e-5
      optimizer: "AdamW"
      scheduler: "CosineAnnealingLR"
      rec_loss_type: l2
      kl_weight: 0.000001
      perceptual_weight: 0.0

data:
  target: data.build.DataModuleFromConfig
  params:
    batch_size: 27
    num_workers: 8
    wrap: false
    train:
      target: data.dataset.SolarDataset_v2.multimodal_dataset
      params:
        modal_list: ['hmi', '0094', '0131', '0171', '0193', '0211', '0304', '0335', '1600', '1700', '4500']
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 0
          - 5000
        time_step: 1
    validation:
      target: data.dataset.SolarDataset_v2.multimodal_dataset
      params:
        modal_list: ['hmi', '0094', '0131', '0171', '0193', '0211', '0304', '0335', '1600', '1700', '4500']
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 5000
          - 5400
        time_step: 1


training:
  # device: 0
  epochs: 100
  test_freq: 100
  save_freq: 100
  contrast_weight_min: 0.001
  contrast_weight_max: 0.005
  reconstruct_weight: 1
  kl_weight: 0.000001
  img_local: True
  full_model_train: True
  mean_logit: False